// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkjGFoc_VoMMJ6oVcQDodVm6yIQtFDTS4',
    appId: '1:1098343742182:web:abd2b60f48595980f55927',
    messagingSenderId: '1098343742182',
    projectId: 'akhbar-app-push-notification',
    authDomain: 'akhbar-app-push-notification.firebaseapp.com',
    storageBucket: 'akhbar-app-push-notification.appspot.com',
    measurementId: 'G-2D7NWC38TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPSIBIO6ujntFwLydYQvQOJ7Ia7t4SNGQ',
    appId: '1:547438027202:android:62d654a2741cd4cd8e365b',
    messagingSenderId: '547438027202',
    projectId: 'akhbar-mashriq',
    storageBucket: 'akhbar-mashriq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6UE7TM-8CN0c4Alrfh7jxlycZ-VPNfM',
    appId: '1:547438027202:ios:428f47a993008bd78e365b',
    messagingSenderId: '547438027202',
    projectId: 'akhbar-mashriq',
    storageBucket: 'akhbar-mashriq.firebasestorage.app',
    iosBundleId: 'com.akhbarmashriq.akhbar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg5t9-zOuZP1d9dPipzrvCep2Pw3B_UuM',
    appId: '1:1098343742182:ios:03a60baa5703b1fdf55927',
    messagingSenderId: '1098343742182',
    projectId: 'akhbar-app-push-notification',
    storageBucket: 'akhbar-app-push-notification.appspot.com',
    iosBundleId: 'com.example.akhbar',
  );
}
